version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: install
          command: npm i;
      - run:
          name: test
          command: npm run test
      - run:
          name: release to chromatic
          command: npm run chromatic -- --project-token=${chromaticProjectToken}
